@startuml

/' diagram meta data start
config=CallConfiguration;
{
  "rootMethod": "com.example.todo.service.TodoService#updateTodo(Long,TodoRequest)",
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": true,
    "cutInterfaceStructures": true,
    "cutDataStructures": true,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showMethodParametersTypes": false,
    "showMethodParametersNames": false,
    "showMethodReturnType": false,
    "showPackageLevels": 2,
    "showCallOrder": false,
    "edgeMode": "MethodsOnly", // TypesOnly, MethodsOnly, TypesAndMethods, MethodsAndDirectTypeUsage
    "showDetailedClassStructure": false
  },
  "rootClass": "com.example.todo.service.TodoService",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="LR"
    splines=polyline
    

'nodes 
subgraph cluster_1322970774 { 
   	label=example
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_134356406 { 
   	label=todo
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   subgraph cluster_1370254625 { 
   	label=TodoService
	labeljust=l
	fillcolor=white
	style=filled
   
   TodoService1007031646XXXupdateTodo1833780167[
	label="+ updateTodo()"
	style=filled
	fillcolor=white
	tooltip="TodoService

null"
	penwidth=4
	fontcolor=darkgreen
];
} 

subgraph cluster_1591292829 { 
   	label=TodoController
	labeljust=l
	fillcolor=white
	style=filled
   
   TodoController1799477165XXXupdateTodo1833780167[
	label="+ updateTodo()"
	style=filled
	fillcolor=white
	tooltip="TodoController

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_1753559203 { 
   	label=TodoMapper
	labeljust=l
	fillcolor=white
	style=filled
   
   TodoMapper1573216920XXXtodoResponse1905346537[
	label="+ todoResponse()"
	style=filled
	fillcolor=white
	tooltip="TodoMapper

null"
	fontcolor=darkgreen
];
} 
} 
} 

'edges    
TodoController1799477165XXXupdateTodo1833780167 -> TodoService1007031646XXXupdateTodo1833780167;
TodoService1007031646XXXupdateTodo1833780167 -> TodoMapper1573216920XXXtodoResponse1905346537;
    
}
@enduml